### ISSUE TITLE
Processwire 1-Click Support

### ISSUE THREAD

**Issue by mminglis** [apisnetworks/apnscp#30]
Know you are busy so will leave this here.

My preferred cms. Active dev community and user base, most would be hosting in dedicated / vps environments.

[Installation](https://processwire.com/docs/start/install/new/#installation-from-zip-file)
[Cli](https://github.com/wireshell/wireshell) (unmaintained but very clean code and works)
[Site / plugin updater by core dev](https://github.com/ryancramerdesign/ProcessWireUpgrade)
[Community site](https://processwire.com/talk/)

Core update just involves new /wire/ and /index.php and optionally new .htaccess.

Min: /site/config.php
Max: /site/assets

**Comment by mminglis** [comment]
Also https://gitlab.com/baumrock/kickstart, lots of plain php with no dependencies for installation. I am going to try to get this going, will msg on discord if I make it somewhere.

**Comment by msaladna** [comment]
Let's say there's room for 1 more 1-click app, why Processwire over Prestashop or NextCloud or Grav or Matomo or RocketChat? Magento was jettisoned as a 1-click because of intrinsic requirements to run well is outside the traditional setup (e.g. Varnish is required). There's a need for Prestashop or a simple e-commerce platform. The list of apps should be thin and should be carefully curated to avoid creating additional burden outside its core competency.

This gives rise to two alternatives:

1. Building a framework to inject 1-clicks as packages in config/custom/ 
    - Offloads development cost and gives the community/developers an opportunity to share their software. This will be done down the road.
2. Adding a generic webapp configuration profile for a site that influences on Web Apps behaves, such as fetching database credentials for comprehensive versioning support and Fortification profiles.
    - Named .webapp.yml in the document root we could control several behaviors in a simple format,
    ```yaml
     # For /var/www/somewhere/public, the docroot of domain.com
     # Otherwise assume approot = docroot
     approot: /var/www/somewhere
     fortify:
       max:
         - /site/assets
       min: 
         - /site/assets
         - /config.php
     # chdir's into approot before query
     db_query: >-
       php -r 'include("./db-config"); print json_encode(['db' => $db, 'user' => $user]);'
     valid: >-
       php -r '$ret = file_exists("./some/unique/file.php"); exit($ret ? 0 : 1);'
     ```

With option 2, it's agnostic, can be easily relocated, and works with any site without requiring a Web App module to effect.

## Concerns
What happens if I'm sloppy with permissions and an attacker wants to inject arbitrary commands that are run against the user's account during an automated panel task. First line of defense is to ensure ownership on .webapp.yml matches the folder owner (typically not web user). Second, ensure permissions are 600. If Fortification is followed, the web app directory will always be different than the web user. 

Second line of defense is to hash parsed metadata. This is simple to do using the account's *sectoken* field, which is unique to each user and generated only once. ApisCP can validate data consistency against the HMAC hash (keyed from *sectoken*). An attacker would thus require panel access to adulterate .webapp.yml.

## Implementation
A general purpose "webapps" module is coming that allows for easy recognition of Web App subtypes. Resolution would first check for .webapp.yml then fall back to checking against subtypes (WordPress, Drupal, Joomla, etc). This allows for a greater degree of customization beyond stock Fortification profiles. All basic [API calls](https://api.apiscp.com/class-Wordpress_Module.html) (valid, fortify, unfortify, db_config, etc) would apply if a corresponding key exists in .webapp.yml. 

Thoughts?
